name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [develop]

jobs:
  macos:
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: actions/cache@v2
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
      - name: Build and Test
        run: swift test -c release
        env:
          DEVELOPER_DIR: /Applications/Xcode_11.4.app/Contents/Developer

  linux:
    runs-on: ubuntu-latest

    container:
      image: swift:5.2

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
      - name: Build and Test
        run: swift test -c release --enable-test-discovery
